export default {
	Avatar: require('../../assets/icons/ic-avatar.png'),
	Lock: require('../../assets/icons/ic-lock.png'),
	Email: require('../../assets/icons/ic-email.png'),
	Eye: require('../../assets/icons/ic-eye.png'),
	EyeHide: require('../../assets/icons/ic-eye-hide.png'),
	Back: require('../../assets/icons/ic-back.png'),
	Error: require('../../assets/icons/ic-error.png'),
	Success: require('../../assets/icons/ic-success.png'),
	Info: require('../../assets/icons/ic-info.png'),
	Home: require('../../assets/icons/ic-home.png'),
	Device: require('../../assets/icons/ic-device.png'),
	Location: require('../../assets/icons/ic-location.png'),
	Detection: require('../../assets/icons/ic-detection.png'),
	Settings: require('../../assets/icons/ic-settings.png'),
}
